version: '3.8'

services:
  bot:
    build: .
    container_name: newdevmaroc_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
